algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var
numero1,numero2: inteiro

inicio
escreva("digite o primeiro numero:")
leia(numero1)
escreva("digite o segundo numero:")
leia(numero2)
 se (numero1=numero2) entao
   escreva("Os numeros sao iguais.")
senao 
   escreva("Os numeros sao diferentes.")
fimse
fimalgoritmo