algoritmo "Nome do Programa"
// crie um programa que verifique o numero que o usuario digitar que sera positivo ou negativo.
var
numero: inteiro

inicio
    escreva("digite o numero:")
      leia(numero)

    se (numero > 0) entao 
    escreva("positivo")
      senao se (numero = 0) entao
             escreval("numero neutro")
          senao 
             escreva("negativo")
         fimse
    fimse
fimalgoritmo