algoritmo "Nome do Programa"
// 17- crie um programa que verifique se um numero e negativo ou maior que 100,
var
//declarar a variavel
numero:real

inicio
// usuario digitar o numero para guarda na memoria
escreva("digite um numero escolhido: ")
leia(numero)
 
// condicional
se (numero >1 > 100)= (numero<100) entao 
escreva("O numero e menor e que 100 e positivo")

senao se (numero= 0) entao
escreva("O numero esta entre 0 e 100 e positivo")

senao  se (numero = 0) entao 
escreva("Esse numero e neutro")

senao
  escreval("Esse numero e negativo")
fimse
fimse
fimse
fimalgoritmo